#!/bin/sh

# Get the commit message file path
shopt -s nocasematch
#MSG_FILE=$1
#if [[ -z $(grep '[^[:space:]]' $MSG_FILE) ]] ; then

#    echo "You can't just commit without a message !!" >&2
#    exit 1
#fi
#!/bin/bash

INPUT_FILE=$1
START_LINE=head -n1 $INPUT_FILE
#PATTERN="^(MYPROJ)-[0-9]"
PATTERN="(PROJ-[0-9]+)"
if ! [[ "$START_LINE" =~ $PATTERN ]];then
  echo "Bad commit message,kindly add the jira to make a commit"
  exit 1
fi
